#!/bin/bash
# SBATCH --nodes=1
# SBATCH --ntasks=1
# SBATCH --cpus-per-task=18
# SBATCH --gpus=1
# SBATCH --partition=gpu
# SBATCH --time=01:00:00
#SBATCH --mail-type=BEGIN,END
#SBATCH --mail-user=jesse.wijlhuizen@hotmail.com

#Loading modules
module load Python/3.10.11

# Execute program located in $HOME
srun C:/Users/jesse/OneDrive/Documenten/GitHub/MScThesis-Sparsity-and-Quickselection/QuickSelection-main/QuickSelection/main.py

https://servicedesk.surf.nl/wiki/pages/viewpage.action?pageId=30660216